config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root :to => "events#home"

  resources :events, :only => [:index, :new, :create, :show]
  # get 'events/index'
  # get 'events/new'
  # get 'events/create'
  # get 'events', to: 'events#index'
  # post 'events', to: 'events#create'
  # get 'events/:id', to: 'events#show'
  
  
  resources :tickets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates :artist, presence: true
    validates :price_low, presence: true, numericality: true
    validates :price_high, presence: true, numericality: true
    validates :event_date, presence: true
    has_many :tickets

    validate :event_date_not_from_past, :price_low_not_higher_than_price_high

    def event_date_not_from_past
        if event_date < Date.today
            errors.add('Event date', 'can not be date from the past.')
        end
    end

    def price_low_not_higher_than_price_high
        if price_low > price_high
            errors.add('Low price', 'has to be lower than high price.')
        end
    end


end

app/models/ticket.rb
class Ticket < ApplicationRecord
    validates :name, presence: true, length: {minimum: 6}
    validates :seat_id_seq, presence: true
    validates :email_address, presence: true
    validates :price, presence: true
    validates :address, presence: true
    validates :phone, presence: true
    
    belongs_to :event
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :check_logged_in, :only => [:new, :create]

  def check_logged_in
        authenticate_or_request_with_http_basic("Ads") do |username, password|
        username == "admin" && password == "admin"
    end
  end

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    # render plain: params[:event].inspect
    @event = Event.new(event_params)
 
    if @event.save
        flash[:komunikat] = 'Event added successfully'
        redirect_to "/events/#{@event.id}"
    else
        render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

private
  def event_params
    params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date)
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]


  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    # @ticket = Ticket.new
    @ticket = Ticket.new( :event_id => params[:event_id], :user_id => current_user.id)
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :event_id, :user_id)
    end

    def correct_user
        @ticket = current_user.tickets.find_by(id: params[:id])
        redirect_to tickets_path, notice: "Nie jesteś uprawniony do edycji tego biletu" if @ticket.nil?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_new_ticket.html.erb
<div class="container buy-ticket-event">
    
    <h2 class="text-center">Book a ticket for the event</h2>

    <%= form_with(model: ticket, local: true) do |form| %>
    <div class="row">
      
        <% if ticket.errors.any? %>
            <div id="error_explanation">
            <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

            <ul>
                <% ticket.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
            </div>
        <% end %>

        <div class="col-md-4 col-sm-4">

            <div class="form-group">

                <div class="field">
                    <%= form.hidden_field :event_id, :value => ticket.event_id %>
                </div>

                <div class="field">
                    <%= form.hidden_field :user_id, :value => ticket.user_id %>
                </div>

                <div class="field">
                    <%= form.label :name %>
                    <%= form.text_field :name, class: "form-control" %>
                </div>

                <div class="field">
                    <%= form.label :email_address %>
                    <%= form.text_field :email_address, class: "form-control" %>
                </div>

            </div>
            
        </div>

        <div class="col-md-4 col-sm-4">

            <div class="field">
                <%= form.label :address %>
                <%= form.text_area :address, class: "form-control" %>
            </div>

            <div class="field">
                <%= form.label :phone %>
                <%= form.text_field :phone, class: "form-control" %>
            </div>
       
        </div>

        <div class="col-md-4 col-sm-4">
            <div class="field">
                <%= form.label :seat_id_seq %>
                <%= form.text_field :seat_id_seq, class: "form-control" %>
            </div>

             <div class="field">
                <%= form.label :price %>
                <%= form.text_field :price, class: "form-control" %>
            </div>
        </div>

    </div>
    
    <div class="row text-center" style="margin-top: 20px;  margin-bottom: 15px;">
        <div class="actions">
            <%= form.submit 'Book ticket', :class => "btn btn-default" %>
        </div>
    </div>

    <% end %>
</div>

app/views/events/_tickets_list.html.erb
<div class="container list-tickets-event">
<p id="notice"><%= notice %></p>

<h2 class="text-center">All reserved tickets</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Seat id seq</th>
      <th>Address</th>
      <th>Price</th>
      <th>Email address</th>
      <th>Phone </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.address %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.email_address %></td>
        <td><%= ticket.phone %></td>
        <td><%= link_to 'Show', ticket %></td>
        <% if ticket.user == current_user %>
            <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
            <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/home.html.erb
<div class="container-fluid posters-image">
    <div class="container main-home">
      
            <p class="main-banner"><h2 class="text-center">Explore tickets and events</h2></p>


            <div class="row">

                <div class="col-sm-6 col-md-6" >
                    <div class="thumbnail" style="background-color:rgba(0, 0, 0, 0.3);">
                    <div class="caption" style="background-color:rgba(0, 0, 0, 0.3);">
                        <p class="text-center" style="color:white; font-size: 25px;">Events</p>
                        <p class="panel-desc text-center">Search attractions and experiences in your area.</p>
                        <p class="text-center">
                            <a href="events" class="btn btn-primary" role="button">Explore</a> 
                        </p>
                    </div>
                    </div>
                </div>


                <div class="col-sm-6 col-md-6">
                    <div class="thumbnail" style="background-color:rgba(0, 0, 0, 0.3);">
                    <div class="caption" style="background-color:rgba(0, 0, 0, 0.3);">
                        <p class="text-center" style="color:white; font-size: 25px;">Tickets</p>
                        <p class="panel-desc text-center">Book a ticket and start your journey !</p>
                        <p class="text-center">
                            <a href="tickets" class="btn btn-primary" role="button">Explore</a> 
                        </p>
                    </div>
                    </div>
                </div>

            </div

        </div>
    </div>
</div>

app/views/events/index.html.erb
<div class="container-fluid events-index-container">

<div class="container events-index">

    <h1 class="text-center" style="color: white;"> List of all future events </h1>


  
    
    <% for event in @events %>
    
    <div class="col-sm-6 col-md-6">

        <div class="panel panel-primary">

            <div class="panel-heading"><%= event.artist%> <%=event.event_date%> </div>
            <div class="panel-body">
                <%= event.description %>
            </div>
            <div class="panel-footer"><button type="button" class="btn btn-default"><%= link_to event.artist, "/events/#{event.id}" %></button></div>

        </div>
    </div>

    <% end %>

    <%= link_to 'Add new event', new_event_path %>

</div>

</div>

app/views/events/new.html.erb
<%= link_to 'Back', events_path %>

<%= form_with scope: :event, url: events_path, local: true do |form| %>
  
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@event.errors.count, "error") %> prohibited
        this event from being saved:
      </h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= form.label :artist %><br>
    <%= form.text_field :artist %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :price_low %><br>
    <%= form.number_field :price_low %>
  </p>

   <p>
    <%= form.label :price_high %><br>
    <%= form.number_field :price_high %>
  </p>

  <p>
    <%= form.label :event_date %><br>
    <%= form.date_field :event_date %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/events/show.html.erb
<div class="container-fluid events-index-container">

<p id="komunikat"> <%=flash[:komunikat]%> </p>

<div class="container event-details">

    <div class="row">
        <h2 class="text-center">Event details</h2>
        <button type="button" class="btn btn-default text-right back-button">   <%= link_to 'Back to all events', events_path %> </button>
    </div>


    <div class="row">
        
        <div class="col-md-4 text-center">
            <p> <strong>Artist:</strong> <%= @event.artist %> </p>
            <p> <strong>Description:</strong> <%= @event.description %> </p>
        </div>
        
        <div class="col-md-4 text-center">
            <p> <strong>LowPrice:</strong> <%= @event.price_low %> </p>
            <p> <strong>PriceHigh:</strong> <%= @event.price_high %> </p>
        </div>

        <div class="col-md-4 text-center">
            <strong>Date:</strong> <%= @event.event_date %>
        </div>
        
    </div>

</div>

<% if user_signed_in? %>
    <%= render "new_ticket", ticket: Ticket.new( :event_id=>@event.id, :user_id => current_user.id) %>
<% end %>

<%= render "tickets_list", tickets: @event.tickets %>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" style="margin-bottom: 0!important;">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Tickets4Events', root_path, :class => 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">

    </ul>
    <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="navbar-brand"> Logged in as <strong><%= current_user.email %></strong>. </li>
            <li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
            <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> </li>
        <% else %>
            <li> <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> </li>
            <li> <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %> </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bilety</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'events' %>
    <%= stylesheet_link_tag 'tickets' %>
  </head>

  <body style="font-family: 'Raleway', sans-serif;">
    
    <%= render 'layouts/header' %>
   
    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/tickets/_events_list.html.erb
<h1 class="text-center"> All events</h1>

    <div class="row">

        <% for event in events %>
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <%= event.artist %> <%= link_to 'New Ticket', new_ticket_path(:event_id => event.id) %>
                </div>
            </div>
        </div>
        <% end %>

    </div>

app/views/tickets/_form.html.erb
<div class="row">

   
        <%= form_with(model: ticket, local: true) do |form| %>
        <% if ticket.errors.any? %>
            <div id="error_explanation">
            <h2 style="color: white; text-align: center;"><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

            <ul class="text-center" style="list-style: none;">
                <% ticket.errors.full_messages.each do |message| %>
                <li style="color: white"><%= message %></li>
                <% end %>
            </ul>
            </div>
        <% end %>
    

    <div class="col-md-4">
    </div>

    <div class="col-md-4"> 
    <div class="field">
        <%= form.hidden_field :event_id, :value => ticket.event_id %>
    </div>

    <div class="field">
        <%= form.hidden_field :user_id, :value => ticket.user_id %>
    </div>

    <div class="field">
        <%= form.label :name, style: "color: white" %>
        <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="field">
        <%= form.label :seat_id_seq, style: "color: white" %>
        <%= form.text_field :seat_id_seq, class: "form-control" %>
    </div>

    <div class="field">
        <%= form.label :address, style: "color: white" %>
        <%= form.text_area :address, class: "form-control" %>
    </div>

    <div class="field">
        <%= form.label :price, style: "color: white" %>
        <%= form.text_field :price, class: "form-control" %>
    </div>

    <div class="field">
        <%= form.label :email_address, style: "color: white" %>
        <%= form.text_field :email_address, class: "form-control" %>
    </div>


    <div class="field">
        <%= form.label :phone, style: "color: white" %>
        <%= form.text_field :phone, class: "form-control" %>
    </div>

    <div class="text-center" style="margin-top: 20px;  margin-bottom: 15px;">
        <div class="actions">
            <%= form.submit 'Save ticket', :class => "btn btn-default" %>
        </div>
    </div>

    <% end %>
    </div>

    <div class="col-md-4">
    </div>

</div>

app/views/tickets/edit.html.erb
<div class="container-fluid tickets-form-container">

    <h1 class="text-center">Editing Ticket</h1>

    <%= render 'form', ticket: @ticket %>

    <div class="tickets-edit-links">
        <button type="button" class="btn btn-default text-right"> <%= link_to 'Show', @ticket %> </button>
        <button type="button" class="btn btn-default text-right"> <%= link_to 'Back', tickets_path %> </button>
    </div>

</div>

app/views/tickets/index.html.erb
<div class="container tickets-index">

    <%= render "events_list", events: Event.all %>

    <p id="notice"><%= notice %></p>

    <h2 class="text-center">All reserved tickets</h2>

    <table class="table table-striped">
    <thead>
        <tr>
        <th>Name</th>
        <th>Seat id seq</th>
        <th>Address</th>
        <th>Price</th>
        <th>Email address</th>
        <th>Phone </th>
        <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @tickets.each do |ticket| %>
        <tr>
            <td><%= ticket.name %></td>
            <td><%= ticket.seat_id_seq %></td>
            <td><%= ticket.address %></td>
            <td><%= ticket.price %></td>
            <td><%= ticket.email_address %></td>
            <td><%= ticket.phone %></td>
            <td><%= link_to 'Show', ticket %></td>
            <% if ticket.user == current_user %>
                <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
                <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
    </table>

    <br>

</div>

app/views/tickets/new.html.erb
<div class="container-fluid tickets-form-container">

    <h1 class="text-center">New Ticket</h1>

    <%= render 'form', ticket: @ticket %>

    <div class="tickets-edit-links">
        <button type="button" class="btn btn-default text-right">  <%= link_to 'Back', tickets_path %> </button>
    </div>

</div>

app/views/tickets/show.html.erb
<div class="container-fluid show-container">

<div class="container">
    <p id="notice"><%= notice %></p>

    <h2 class="text-center" style="color: white">Your ticket </h2>
    
    <div class="card-custom">
    <img src="https://source.unsplash.com/ZhQCZjr9fHo/" alt="Concert image" style="width:100%">
        <div class="container-card">
            <h4><b><strong>Name: </strong><%= @ticket.name %></b> | <strong>Seat id seq:</strong> <%= @ticket.seat_id_seq %></h4> 
            <p><strong>Address:</strong> <%= @ticket.address %> |     <strong>Price:</strong> <%= @ticket.price %></p> 
            <p><strong>Email address:</strong> <%= @ticket.email_address %> </p>
            <p><strong>Phone:</strong> <%= @ticket.phone %> </p>
        </div>
    </div>

    <div class="row text-center" style="margin-top: 20px">

        <% if @ticket.user == current_user %>
            <button class="btn btn-default"> <%= link_to 'Edit', edit_ticket_path(@ticket) %> </button>
        <% end %>

         <button class="btn btn-default">  <%= link_to 'Back', tickets_path %> </button>
    
    </div>

</div>

</div>